import React from 'react';
import Image from 'next/image';

interface PackingSlipHTMLProps {
  invoice: any;
  logoUrl?: string;
}

export const PackingSlipHTML = React.forwardRef<HTMLDivElement, PackingSlipHTMLProps>(({ invoice, logoUrl }, ref) => {
  const { customer, items } = invoice;

  return (
    <div 
      ref={ref}
      className="bg-white text-black p-10 w-[794px] h-[1123px] mx-auto box-border relative font-sans"
      style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}
    >
      {/* Header */}
      <div className="flex justify-between border-b-2 border-black pb-5 mb-10">
        <div>
          {logoUrl && (
            <div className="mb-2 w-16 h-16 relative">
              <img src={logoUrl} alt="Logo" className="object-contain w-full h-full" />
            </div>
          )}
          <div className="text-base font-bold uppercase tracking-widest mb-1">NB57's Nostalgia</div>
        </div>
        <div className="text-right flex flex-col items-end">
          <div className="text-2xl font-bold uppercase tracking-[0.15em] mb-2">PACKING SLIP</div>
          <div className="text-[10px] text-gray-800 mb-1">
            <span className="font-bold mr-1">Order No:</span> {invoice.invoiceNumber}
          </div>
          <div className="text-[10px] text-gray-800 mb-1">
            <span className="font-bold mr-1">Date:</span> {new Date().toLocaleDateString('en-IN')}
          </div>
        </div>
      </div>

      {/* Addresses */}
      <div className="flex justify-between mb-8">
        <div className="w-[45%]">
          <div className="text-xs font-bold uppercase tracking-wide border-b border-gray-200 pb-1 mb-2">Ship To</div>
          <div className="text-xs font-bold mb-1">{customer.name}</div>
          {customer.address && <div className="text-[10px] text-gray-800 mb-1">{customer.address}</div>}
          <div className="text-[10px] text-gray-800 mb-1">
            {[customer.city, customer.state, customer.pin].filter(Boolean).join(', ')}
          </div>
          {customer.country && <div className="text-[10px] text-gray-800 mb-1">{customer.country}</div>}
          {customer.phone && <div className="text-[10px] text-gray-800 mb-1">Phone: {customer.phone}</div>}
        </div>
        
        <div className="w-[45%]">
          <div className="text-xs font-bold uppercase tracking-wide border-b border-gray-200 pb-1 mb-2">Return Address</div>
          <div className="text-xs font-bold mb-1">NB57's Nostalgia</div>
          <div className="text-[10px] text-gray-800 mb-1">BC-2 West, Shalimar bagh</div>
          <div className="text-[10px] text-gray-800 mb-1">Delhi-110088</div>
        </div>
      </div>

      {/* Items Table */}
      <div className="w-full mb-8">
        <div className="flex border-b border-black pb-2 mb-2">
          <div className="text-[10px] font-bold uppercase tracking-wide w-[10%]">Pack</div>
          <div className="text-[10px] font-bold uppercase tracking-wide w-[50%]">Item Description</div>
          <div className="text-[10px] font-bold uppercase tracking-wide w-[30%]">Collection ID</div>
          <div className="text-[10px] font-bold uppercase tracking-wide w-[10%] text-center">Qty</div>
        </div>
        
        {items.map((item: any) => (
          <div key={item.id} className="flex border-b border-gray-200 pb-2 mb-2 items-center">
            <div className="w-[10%]">
              <div className="w-3 h-3 border border-black"></div>
            </div>
            <div className="text-[11px] w-[50%]">{item.itemName}</div>
            <div className="text-[11px] w-[30%]">{item.itemSku}</div>
            <div className="text-[11px] w-[10%] text-center">{item.quantity}</div>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="absolute bottom-10 left-10 right-10 text-center border-t border-gray-200 pt-5">
        <div className="text-[10px] text-gray-500 mb-1">Please check off items as they are packed.</div>
        <div className="text-[10px] text-gray-500 mb-1">Generated by NB57's Nostalgia</div>
      </div>
    </div>
  );
});

PackingSlipHTML.displayName = 'PackingSlipHTML';
